//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Orzyourself.UserLimit.MODEL
{
    using Newtonsoft.Json;//添加引用
    using System;
    using System.Collections.Generic;
    
    public partial class BaseUser
    {
        public BaseUser()
        {
            this.R_User_Permission = new HashSet<R_User_Permission>();
            this.R_User_Role = new HashSet<R_User_Role>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string RealName { get; set; }
        public string QuickQuery { get; set; }
        public Nullable<int> SecurityLevel { get; set; }
        public string UserFrom { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> SubCompanyID { get; set; }
        public string SubCompanyName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> WorkgroupID { get; set; }
        public string WorkgroupName { get; set; }
        public string WorkCategory { get; set; }
        public Nullable<System.DateTime> ChangePasswordDate { get; set; }
        public string Duty { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Lang { get; set; }
        public string Gender { get; set; }
        public string Birthday { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string QICQ { get; set; }
        public string HomeAddress { get; set; }
        public string Theme { get; set; }
        public Nullable<int> IsStaff { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public string UserAddRessID { get; set; }
        public Nullable<int> Enabled { get; set; }
        public string AuditStatus { get; set; }
        public Nullable<int> DeletionStateCode { get; set; }
        public string Signature { get; set; }
        public Nullable<int> SortCode { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreateUserID { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifirdOn { get; set; }
        public string ModifiedUserID { get; set; }
        public string ModifiedBy { get; set; }
       //导航属性
       [JsonIgnore]
        public virtual ICollection<R_User_Permission> R_User_Permission { get; set; }
       [JsonIgnore]
        public virtual ICollection<R_User_Role> R_User_Role { get; set; }
    }
}
